import Question from "components/question";
import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-screen min-h-screen bg-gray-900 p-5 pt-20">
                <div className="questions max-w-3xl p-2 mx-auto  bg-gray-700">
                    <Question />
                </div>
            </main>
        </div>
    );
}
